apiVersion: apps/v1beta2
kind: Deployment
metadata:
        name: iot-backend
spec:
        selector:
                matchLabels:
                        app: iot-backend
        replicas: 1
        template:
                metadata:
                        labels:
                                app: iot-backend
                spec:
                        containers:
                                - name: iot-backend
                                  image: gcr.io/graphic-tensor-197007/iot-backend:0.1
                                  ports:
                                          - containerPort: 9000
