apiVersion: apps/v1beta2
kind: Deployment
metadata:
        name: iot-frontend
spec:
        selector:
                matchLabels:
                        app: iot-frontend
        replicas: 4
        template:
                metadata:
                        labels:
                                app: iot-frontend
                spec:
                        containers:
                                - name: iot-frontend
                                  image: gcr.io/graphic-tensor-197007/iot-frontend:0.10
                                  ports:
                                          - containerPort: 8000
