apiVersion: v1
kind: Service
metadata:
        name: frontend-service
        labels:
                app: iot-frontend
spec:
        type: LoadBalancer
        ports:
                - port: 8000
                  protocol: TCP
        selector:
                app: iot-frontend
